name: Deploy Snapshots

on:
  push:
    branches: ['main']

  repository_dispatch:
    types: ['deploy-snapshots']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Enable caching of Maven dependencies
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up Java 1.8 with Maven and authentication for deploy
      - name: Set up JDK 1.8 and configure Maven for deployment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: openmrs-repo-snapshots
          server-username: BINTRAY_USERNAME
          server-password: BINTRAY_PASSWORD

      # Deploy snapshot using Maven
      - name: Maven Deploy
        run: mvn -B deploy -DskipTests --file pom.xml
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}
