name: Run Tests

on:
  pull_request:
    branches: ['master']

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Enable caching of Maven dependencies using latest cache action
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up Java 1.8 using latest setup-java version
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      # Build and run tests using Maven
      - name: Build and run tests with Maven
        run: mvn clean install
